# +argocd:skip-file-rendering
apiVersion: v1
kind: Secret
metadata:
    name: proclone-secrets
type: Opaque
stringData:
    LDAP_SERVER: your.domain.controller
    PC_PORT: "8080"
    SECRET_KEY: placeholder
    LDAP_BIND_DN: cn=ldap-reader,cn=users,dc=domain,dc=com
    LDAP_BIND_PASSWORD: placeholder
    LDAP_BASE_DN: dc=domain,dc=com
    NETBIOS_NAME: name
    PROXMOX_NODES: node1,node2,node3,...
    PROXMOX_PORT: "8006"
    PROXMOX_SERVER: your.proxmox.server
    PROXMOX_TOKEN_ID: accountname@pve!token-id
    PROXMOX_TOKEN_SECRET: secret-token-hash
    PROXMOX_VERIFY_SSL: true/false

# ALL VALUES IN THIS FILE MUST BE REPLACED WITH YOUR ACTUAL VALUES
