apiVersion: apps/v1
kind: Deployment
metadata:
    name: proclone-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: proclone-backend
    template:
        metadata:
            labels:
                app: proclone-backend
        spec:
            containers:
                - name: proclone-backend
                  image: ghcr.io/cpp-cyber/proclone:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                  env:
                      - name: REDIS_ADDR
                        value: "redis-master.default.svc.cluster.local:6379"
                      - name: REDIS_PASSWORD
                        value: ""
                      - name: STORAGE_ID
                        value: "[your shared storage ID]" 
                      - name: LDAP_SERVER
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: LDAP_SERVER
                      - name: PC_PORT
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PC_PORT
                      - name: SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: SECRET_KEY
                      - name: LDAP_BIND_DN
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: LDAP_BIND_DN
                      - name: LDAP_BIND_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: LDAP_BIND_PASSWORD
                      - name: LDAP_BASE_DN
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: LDAP_BASE_DN
                      - name: PROXMOX_SERVER
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_SERVER
                      - name: PROXMOX_PORT
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_PORT
                      - name: PROXMOX_TOKEN_ID
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_TOKEN_ID
                      - name: PROXMOX_TOKEN_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_TOKEN_SECRET
                      - name: PROXMOX_VERIFY_SSL
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_VERIFY_SSL
                      - name: PROXMOX_NODES
                        valueFrom:
                            secretKeyRef:
                                name: proclone-secrets
                                key: PROXMOX_NODES
